---
name: "Terraform security"
description: "A terraform based security validation github action"

inputs:
  directory:
    description: "Directory in which terraform code is available"
    required: false
    default: "./"
  github_token:
    description: "GitHub token to create security issues and PR comments"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Executing tfsec
      uses: tfsec/tfsec-sarif-action@main
      with:
        sarif_file: tfsec.sarif
        working_directory: ${{ inputs.directory }}
        github_token: ${{ inputs.github_token }}

    - name: Executing tfsec PR commenter
      uses: tfsec/tfsec-pr-commenter-action@main
      with:
        working_directory: ${{ inputs.directory }}
        github_token: ${{ inputs.github_token }}
