---
name: "Terraform security"
description: "A terraform based security validation github action"

inputs:
  directory:
    description: "Directory in which terraform code is available"
    required: false
    default: "./"
  github_token:
    description: "GitHub token to create security issues and PR comments"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Executing tfsec
      uses: aquasecurity/tfsec-sarif-action@v0.1.0
      with:
        sarif_file: tfsec.sarif
        working_directory: ${{ inputs.directory }}
        github_token: ${{ inputs.github_token }}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: tfsec.sarif

    - name: Executing tfsec PR commenter
      uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
      with:
        working_directory: ${{ inputs.directory }}
        github_token: ${{ inputs.github_token }}
